version: "2"
services:
  atlas:
    build: .
    image: atlas:2
    ports:
      - 4200:4200
    volumes:
      - .:/code
    depends_on:
      - selenium
    links:
      - selenium
  selenium:
    image: selenium/standalone-chrome:3.8.1-francium
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
